### ISSUE TITLE
Extracting data with original co-ordinates

### ISSUE THREAD

**Issue by prakashncess** [paudetseis/PlateFlex#4]
I am unable to extract Te data corresponding to original grid format. Can you please let me know the way to get the data?

Thanks

**Comment by paudetseis** [comment]
`PlateFlex` works with cartesian grids and does not provide tools to convert from cartesian to geographic (or vice versa). If you followed the GMT example in the documentation to create the cartesian grids (https://paudetseis.github.io/PlateFlex/getting_started.html#making-gridded-data) then you can perform the reverse operation to obtain the geographic grid from the cartesian grid using GMT tools (e.g., `mapproject` or `grdproject`). 

If you are instead referring to the process of extracting the grid from the `Project` object, you can check out the documentation on the `save_results` method of the `Project` class that dumps the grid into a .csv file.

I am closing this issue as there is no further action required.
