### ISSUE TITLE
Problem resampling CRUST1.0

### ISSUE THREAD

**Issue by icasallas** [paudetseis/PlateFlex#7]
Dear users of plateflex:

I am following the example of the documentation to make a grid for crustal thickness using CRUST1.0.  I got crsthk.xyz file and created  the 1 degree grid file using: 

                gmt xyz2grd crsthk.xyz -Gcrust_thickness_1deg.grd -Rd -I1

However, when I try to resample to 2' grid using:

                  gmt grdsample crust_thickness_1deg.grd -Gcrust_thickness_2m.grd -nb -Rg -I2m

I got a grdsample warning related to no valid values in grid [crust_thickness_2m.grd] and as a consequence a grid full of nan values.

I am using GMT 5.4.3.

Have someone had this problem? Any advice/recommendation.

Thanks in advance.

**Comment by paudetseis** [comment]
This looks like a GMT problem, and this issue should perhaps be reported to the GMT developers. However, these commands are from an older version of GMT and I'm not sure if anyone there would respond. 

Can you post a more detailed error message from the GMT calls? Make sure to add `-V` to get a more verbose message. Also type
`grdinfo crust_thickness_1deg.grd`
and
`grdinfo crust_thickness_2m.grd`

**Comment by icasallas** [comment]
Thanks for your answer. This worked for me using GMT 6.3.0.

     gmt xyz2grd crsthk.xyz -Gcrust_thickness_1deg.grd -Rd -I1 -r

     gmt grdsample crust_thickness_1deg.grd -Gcrust_thickness_2m.grd -nb -Rg -I2m -T
